CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
SHOW_BACKEND_WINDOW = False

SWIPE_THRESHOLD_PX = 80

SWIPE_MAX_DURATION_MS = 1000
SWIPE_MIN_SPEED = 400

INTENT_FIST_SEC = 0.8
INTENT_LASER_SEC = 0.8
INTENT_VOICE_START_SEC = 0.8
INTENT_ILY_SEC = 0.6
INTENT_POWERPOINT_SEC = 0.8

INTENT_QUIT_SEC = 1.0
COOLDOWN_QUIT_MS = 2000

SNAP_DISTANCE_CLOSED = 20
SNAP_DISTANCE_OPEN = 80
SNAP_MAX_FRAMES = 3

COOLDOWN_SWIPE_MS = 1000
COOLDOWN_START_MS = 2000
COOLDOWN_CLOSE_MS = 2000
COOLDOWN_SNAP_MS = 1
COOLDOWN_LASER_TOGGLE_MS = 1500
COOLDOWN_VOICE_START_MS = 3000
COOLDOWN_ILY_MS = 500
ILY_TAB_REPEAT_MS = 600
COOLDOWN_POWERPOINT_MS = 5000
INTENT_NEW_SLIDE_SEC = 0.8
COOLDOWN_NEW_SLIDE_MS = 2000

LASER_MIN_CUTOFF = 0.4
LASER_BETA = 0.007
LASER_D_CUTOFF = 1.0
LASER_BOX_X_MIN = 0.20
LASER_BOX_X_MAX = 0.80
LASER_BOX_Y_MIN = 0.15
LASER_BOX_Y_MAX = 0.85
LASER_DEADZONE_PX = 2

YOLO_CONFIDENCE = 0.5
LOCK_LOST_SEC = 3

MP_DETECTION_CONFIDENCE = 0.7
MP_TRACKING_CONFIDENCE = 0.7

DOCUMENT_SEARCH_PATHS = ["~/Documents", "~/Desktop", "~/Downloads"]
DOCUMENT_SEARCH_EXTENSIONS = [".docx", ".xlsx", ".pptx", ".pdf", ".txt", ".csv"]
DOCUMENT_SEARCH_MAX_RESULTS = 5
DOCUMENT_INDEX_TTL_SEC = 60
DOCUMENT_INDEX_MAX_FILES = 20_000
DOCUMENT_SEARCH_EXCLUDED_DIRS = [
    "__pycache__",
    "node_modules",
    "venv",
    ".venv",
]
